[Hackathon NO.84] 为神经网络编译器 CINN 增加 ReverseComputeInline 原语
PaddlePaddle/CINN pull request #1331
Opened 2023-04-04 10:50 UTC by zrr1999

题目：https://github.com/PaddlePaddle/community/blob/master/hackthon_4th/%E3%80%90PaddlePaddle%20Hackathon%204%E3%80%91%20%E6%A0%B8%E5%BF%83%E6%A1%86%E6%9E%B6%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%20CINN%20%E5%BC%80%E5%8F%91%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#task84

rfc: 
https://github.com/PaddlePaddle/community/pull/465

参考资料：
1. [CINN项目贡献指南](https://github.com/PaddlePaddle/CINN/pull/810)  
2. [CINN IR抽象语法树](https://github.com/PaddlePaddle/CINN/pull/775)  
3. [CINN调度原语开发](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/CINN/CINN_ir_schedule.md) 
4. [玩转飞桨深度学习编译器](https://aistudio.baidu.com/aistudio/education/lessonvideo/4113898)

2023-04-10 12:33 UTC, CtfGo requested changes
@BiynXu 你之前看过CINN中的ComputeInline实现，也帮忙review一下实现

2023-04-10 12:33 UTC, CtfGo commented on cinn/ir/ir_schedule.h
> +   * \brief Mark an schedule block as inlined.
```suggestion
   * \brief  Inline a consumer block into its only producer.
```

2023-04-10 12:33 UTC, CtfGo commented on cinn/ir/ir_schedule.h
> + * \brief Helper to inline its producer(s) block into the consumer
```suggestion
 * \brief Helper to inline a block into the its producer
```

2023-04-10 12:33 UTC, CtfGo commented on cinn/ir/ir_schedule_util.h
> +
注释说明该函数作用

2023-04-10 12:33 UTC, CtfGo commented on cinn/backends/ir_schedule_test.cc
> +
参考如下示例构造测试case：https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/CINN/CINN_ir_schedule.md#5reversecomputeinline。
验证能否产出如文档所示的效果。
```suggestion
  Expr M(32);
  Expr N(64);

  Target target = common::DefaultHostTarget();

  Placeholder<float> A("A", {M, N, P});
  auto B = Compute(
      {M, N}, [&](Var i, Var j) { return Expr(1.f) + A(i, j); }, "B");
  auto C = Compute(
      {N, M}, [&](Var i, Var j) { return Expr(2.f) * B(j, i);}, "C");

```

2023-04-13 14:04 UTC, BiynXu commented on cinn/backends/ir_schedule_test.cc
> +        C[((1024 * i) + ((32 * j) + k))] = fma(2.00000000f, A[((32 * i) + ((1024 * j) + k))], 2.00000000f);
这种情况下应该为：
C[((32 * i) + ((1024 * j) + k))] = fma(2.00000000f, A[((1024 * i) + ((32 * j) + k))], 2.00000000f);
ReverseComputeInline需要将consumer 融合到 producer中，也就是将C的计算融合进 Block B中，因此保留Block B的相关循环结构，读取A的顺序与循环顺序相同，写入C的顺序i, j调换。

2023-04-13 14:21 UTC, zrr1999 commented on cinn/ir/ir_schedule_util.h
> +
好的，已添加

2023-04-13 16:20 UTC, zrr1999 commented on cinn/backends/ir_schedule_test.cc
> +
好的，这里我已经改成了文档中的形式

2023-04-14 06:57 UTC, zrr1999 commented on cinn/backends/ir_schedule_test.cc
> +        C[((1024 * i) + ((32 * j) + k))] = fma(2.00000000f, A[((32 * i) + ((1024 * j) + k))], 2.00000000f);
好的，这块已经修复啦

2023-04-18 06:17 UTC, zrr1999 commented on cinn/ir/ir_schedule.h
> +   * \brief Mark an schedule block as inlined.
好的，已修改

2023-04-18 06:17 UTC, zrr1999 commented on cinn/ir/ir_schedule.h
> + * \brief Helper to inline its producer(s) block into the consumer
好的，已修改

2023-04-18 12:43 UTC, CtfGo approved these changes, later dismissed
LGTM. @BiynXu 你也看下

2023-04-19 11:40 UTC, BiynXu commented on cinn/ir/ir_schedule.cc
> +  //  Expr inlined_store = CheckReverseComputeInlineValidationAndGetStore(schedule_block, root);
无用代码可以进行删除，不留注释

2023-04-19 11:40 UTC, BiynXu commented on cinn/ir/ir_schedule_util.h
> +Expr CheckReverseComputeInlineValidationAndGetStore(const Expr& schedule_block, const Expr& root);
该函数功能已被其他函数替代，如果没有用到，可以删除，包括其实现。

2023-04-19 14:28 UTC, zrr1999 commented on cinn/ir/ir_schedule_util.h
> +Expr CheckReverseComputeInlineValidationAndGetStore(const Expr& schedule_block, const Expr& root);
好的，已删除这部分

2023-04-19 14:28 UTC, zrr1999 commented on cinn/ir/ir_schedule.cc
> +  //  Expr inlined_store = CheckReverseComputeInlineValidationAndGetStore(schedule_block, root);
好的，已删除这部分

2023-04-20 01:42 UTC, BiynXu approved these changes
LGTM

2023-04-20 01:53 UTC, merged